import { Especialidad, Pregunta } from './especialidad.modelo';

// Práctica NO OFICIAL - Electromecánica (código DGEC 2011)
// Preguntas originales, hechas siguiendo la tabla de especificaciones 2026 (60 ítems):
// Décimo 19, Undécimo 26 y Duodécimo 15, con la cantidad de ítems por evidencia de aprendizaje de la tabla.
// "correcta" usa el orden ORIGINAL de las opciones (0 = A, 1 = B, 2 = C).
// Nota: en la tabla algunas evidencias no traen número (circuitos del Décimo, tipos de cliente y trabajo
// en equipo); aquí se les puso 1.1, 8.1 y 9.1 solo para poder agrupar los resultados.

// Función auxiliar: arma una pregunta (así el archivo queda más corto)
function p(
  id: number, nivel: string, subarea: string, indicador: string, texto: string,
  opciones: string[], correcta: number, justificacion: string
): Pregunta {
  return { id, nivel, subarea, indicador, texto, opciones, correcta, justificacion };
}

// Niveles
const DEC = 'Décimo';
const UND = 'Undécimo';
const DUO = 'Duodécimo';

// Subáreas
const MEC = 'Mecánica básica';
const CIR = 'Circuitos electromecánicos';
const MAQ = 'Máquinas eléctricas';
const AUT = 'Automatismo electromecánico';

// Evidencias de aprendizaje (según la tabla de especificaciones)
const I = {
  // Mecánica básica - Décimo
  mec11: '1.1 Identifica los cuidados que se debe tener con las máquinas, incendios y el orden y limpieza en el taller o laboratorio.',
  mec21: '2.1 Reconoce las reglas de seguridad eléctrica que se deben aplicar en el hogar, la industria y al aire libre.',
  mec31: '3.1 Describe los sistemas de medida y los errores de medición en la construcción mecánica.',
  mec41: '4.1 Cita los conceptos relacionados con la soldadura de fusión.',
  mec42: '4.2 Reconoce los procedimientos para realizar soldadura por fusión.',
  mec51: '5.1 Identifica las características técnicas de los trabajos de soldadura blanda y fuerte.',
  mec52: '5.2 Reconoce los procedimientos para realizar soldadura blanda y fuerte.',
  // Circuitos electromecánicos - Décimo
  cirD11: '1.1 Resuelve problemas en circuitos serie, paralelo y mixto, utilizando las leyes de Ohm, Kirchhoff y Watt.',
  cirD21: '2.1 Realiza mediciones de tensión, corriente y resistencia con el multímetro (analógico y digital).',
  cirD31: '3.1 Suma capacitancias e inductancias en serie y paralelo.',
  cirD41: '4.1 Reconoce las diferentes magnitudes que intervienen en una onda senoidal.',
  cirD51: '5.1 Resuelve problemas de reactancias en serie y paralelo.',
  cirD61: '6.1 Compara el funcionamiento y la curva característica del diodo rectificador, diodo Zener y el diodo emisor de luz.',
  cirD71: '7.1 Relaciona el funcionamiento de los rectificadores de media onda con el de onda completa.',
  // Máquinas eléctricas - Undécimo
  maq11: '1.1 Explica las partes fundamentales de las máquinas eléctricas.',
  maq12: '1.2 Reconoce las diferentes funciones y tipos de máquinas eléctricas.',
  maq21: '2.1 Describe los materiales aislantes y conductores empleados en máquinas eléctricas.',
  maq31: '3.1 Determina pérdidas de potencia en máquinas eléctricas de acuerdo con datos técnicos.',
  maq41: '4.1 Reconoce los datos y características técnicas de generadores de C.C.',
  maq51: '5.1 Reconoce las partes y tipos del alternador automotriz.',
  maq61: '6.1 Reconoce los datos y características técnicas de los motores de C.A.',
  maq71: '7.1 Reconoce los datos y características técnicas de los transformadores monofásicos y trifásicos.',
  maq81: '8.1 Distingue los tipos de cliente.',
  maq91: '9.1 Explica las características que adoptan las personas al trabajar en equipo.',
  // Automatismo electromecánico - Undécimo
  autU11: '1.1 Reconoce los circuitos típicos con los diferentes elementos de disparo.',
  autU21: '2.1 Nombra las características técnicas de los SCR y el TRIAC.',
  autU31: "3.1 Resuelve circuitos con IGBT's.",
  autU41: '4.1 Señala los principios de funcionamiento del oscilador integrado 555 o su equivalente.',
  autU51: '5.1 Nombra las características técnicas de los amplificadores operacionales.',
  autU61: '6.1 Cita las aplicaciones en la industria de los interruptores termomagnéticos de alta capacidad interruptiva.',
  autU71: '7.1 Selecciona dispositivos de maniobra, mando y señalización, utilizados en circuitos de control a contactores.',
  autU72: '7.2 Clasifica los diferentes temporizadores utilizados en circuitos de control a contactores.',
  autU81: '8.1 Clasifica los arrancadores directos, con y sin inversión de giro.',
  autU91: '9.1 Enumera las características técnicas de diseño de controles para motores de varias velocidades.',
  // Automatismo electromecánico - Duodécimo
  autD101: '10.1 Describe el funcionamiento de cada una de las partes que componen el PLC.',
  autD111: '11.1 Identifica los actuadores neumáticos e hidráulicos, así como las propiedades del aire y de los líquidos.',
  autD121: '12.1 Identifica los pasos para regular los sistemas de distribución.',
  autD131: '13.1 Cita los principios de los robots más utilizados en la industria.',
  // Circuitos electromecánicos - Duodécimo
  cirU11: '1.1 Reconoce los diferentes sistemas de numeración y códigos alfanuméricos.',
  cirU12: '1.2 Realiza conversiones de un sistema numérico a otro y de un código a otro.',
  cirU21: '2.1 Describe las características y el funcionamiento de las compuertas lógicas, así como sus parámetros eléctricos.',
  cirU22: '2.2 Simplifica funciones canónicas y no canónicas utilizando álgebra booleana y mapas de Karnaugh.',
  cirU31: '3.1 Reconoce los principales parámetros funcionales y constructivos de los circuitos digitales TTL y CMOS.',
  cirU41: '4.1 Describe las operaciones aritméticas con números binarios.',
  cirU51: '5.1 Distingue biestables desarrollados a partir de compuertas NAND y NOR.',
  cirU52: '5.2 Describe las características y el funcionamiento de las compuertas lógicas, así como sus parámetros eléctricos.',
};

export const especialidad2011: Especialidad = {
  codigo: '2011',
  nombre: 'Electromecánica',
  duracionMinutos: 180,
  preguntas: [
    // ===== DÉCIMO - Mecánica básica (1-10) =====
    p(1, DEC, MEC, I.mec11,
      'En un taller, ¿cuál es una medida correcta para prevenir accidentes con las máquinas?',
      ['Retirar las guardas de protección para trabajar más rápido', 'Usar las máquinas solo con las guardas colocadas y con la autorización correspondiente', 'Operarlas con ropa suelta para mayor comodidad'], 1,
      'Las guardas protegen las partes móviles; retirarlas o usar ropa suelta aumenta el riesgo de atrapamiento.'),
    p(2, DEC, MEC, I.mec11,
      'Se produce un incendio en un tablero eléctrico energizado. ¿Qué extintor es el más adecuado?',
      ['De agua a presión', 'De espuma', 'De CO₂ o de polvo químico seco'], 2,
      'El agua y la espuma conducen electricidad. El CO₂ y el polvo químico seco son adecuados para fuegos de origen eléctrico.'),
    p(3, DEC, MEC, I.mec21,
      'Antes de intervenir un circuito eléctrico, ¿qué debe hacerse primero?',
      ['Desenergizar el circuito, bloquearlo y verificar que no haya tensión', 'Tocar los conductores con el dorso de la mano para comprobar si hay energía', 'Trabajar con las manos húmedas para tener mejor contacto'], 0,
      'La regla básica es desenergizar, bloquear, etiquetar y verificar la ausencia de tensión antes de trabajar.'),
    p(4, DEC, MEC, I.mec21,
      'Un técnico trabaja al aire libre en una instalación eléctrica y comienza una tormenta eléctrica. ¿Qué debe hacer?',
      ['Continuar el trabajo para terminar antes', 'Refugiarse bajo un árbol aislado', 'Suspender el trabajo y buscar un refugio seguro'], 2,
      'Con tormenta eléctrica hay riesgo de descarga; se debe suspender el trabajo y refugiarse en un lugar seguro, no bajo árboles ni estructuras altas.'),
    p(5, DEC, MEC, I.mec31,
      'Un técnico lee siempre 0,2 mm de más porque el instrumento está mal calibrado. ¿Qué tipo de error de medición es?',
      ['Error sistemático', 'Error aleatorio', 'Error de redondeo del fabricante'], 0,
      'Un error que se repite siempre con el mismo valor y sentido es sistemático. Los aleatorios varían de una lectura a otra.'),
    p(6, DEC, MEC, I.mec41,
      'En la soldadura por fusión, ¿qué ocurre con los metales base y el material de aporte?',
      ['Se unen sin fundirse, solo por presión', 'Se funden en la zona de unión y al enfriarse forman la junta', 'Se pegan con un adhesivo a temperatura ambiente'], 1,
      'La soldadura por fusión funde el metal en la unión, y al solidificarse las piezas quedan unidas.'),
    p(7, DEC, MEC, I.mec41,
      '¿Cuál es la función del revestimiento de un electrodo en la soldadura por arco eléctrico?',
      ['Servir de mango aislante para el soldador', 'Aumentar la corriente del arco', 'Generar gases y escoria que protegen el metal fundido'], 2,
      'El revestimiento produce gases y escoria que protegen el baño de fusión del aire y estabilizan el arco.'),
    p(8, DEC, MEC, I.mec42,
      'Antes de soldar con arco eléctrico, ¿qué procedimiento es correcto?',
      ['Limpiar las piezas de óxido, pintura y grasa y usar el equipo de protección personal', 'Soldar sobre la pintura para que la junta quede más resistente', 'Prescindir de la careta si la soldadura es corta'], 0,
      'Las piezas deben estar limpias para una buena unión y siempre se debe usar careta, guantes y ropa de protección.'),
    p(9, DEC, MEC, I.mec51,
      '¿Cuál es la diferencia principal entre soldadura blanda y soldadura fuerte?',
      ['La fuerte funde a menos de 450 °C y la blanda a más de 450 °C', 'La blanda usa aleaciones que funden por debajo de 450 °C y la fuerte por encima', 'La blanda funde el metal base y la fuerte no'], 1,
      'La soldadura blanda usa aleaciones que funden por debajo de 450 °C; la fuerte, por encima. En ambas el metal base no se funde.'),
    p(10, DEC, MEC, I.mec52,
      'Al soldar con estaño y cautín, ¿qué función cumple el fundente (flux)?',
      ['Enfriar la unión rápidamente', 'Aumentar la resistencia eléctrica de la unión', 'Eliminar óxidos y ayudar a que la soldadura moje la superficie'], 2,
      'El fundente limpia los óxidos y permite que el estaño se adhiera bien a las superficies.'),

    // ===== DÉCIMO - Circuitos electromecánicos (11-19) =====
    p(11, DEC, CIR, I.cirD11,
      'Dos resistores de 10 Ω y 20 Ω se conectan en serie a una fuente de 30 V. ¿Cuál es la corriente del circuito?',
      ['4,5 A', '1 A', '0,5 A'], 1,
      'La resistencia total es 10 + 20 = 30 Ω, entonces I = 30 V / 30 Ω = 1 A.'),
    p(12, DEC, CIR, I.cirD21,
      'Para medir la corriente que circula por una carga con un multímetro, ¿cómo debe conectarse el instrumento?',
      ['En paralelo con la carga y en la escala de voltios', 'Directamente en la toma, sin la carga', 'En serie con la carga, usando la escala de corriente'], 2,
      'El amperímetro se conecta en serie para que toda la corriente del circuito pase por el instrumento.'),
    p(13, DEC, CIR, I.cirD31,
      'Dos capacitores de 6 µF y 3 µF se conectan en serie. ¿Cuál es la capacitancia equivalente?',
      ['9 µF', '2 µF', '4,5 µF'], 1,
      'En serie: Ceq = (6 × 3) / (6 + 3) = 18 / 9 = 2 µF.'),
    p(14, DEC, CIR, I.cirD31,
      'Dos inductores de 4 mH y 6 mH se conectan en serie sin acoplamiento magnético. ¿Cuál es la inductancia total?',
      ['2,4 mH', '5 mH', '10 mH'], 2,
      'En serie las inductancias se suman: 4 mH + 6 mH = 10 mH.'),
    p(15, DEC, CIR, I.cirD41,
      'Una onda senoidal tiene un valor pico de 170 V. ¿Cuál es aproximadamente su valor eficaz (RMS)?',
      ['120 V', '85 V', '240 V'], 0,
      'Vrms = Vpico / √2 = 170 V / 1,414 ≈ 120 V.'),
    p(16, DEC, CIR, I.cirD51,
      '¿Cuál es la reactancia inductiva de una bobina de 0,1 H a 60 Hz? (XL = 2πfL)',
      ['6 Ω', '37,7 Ω', '377 Ω'], 1,
      'XL = 2 × π × 60 × 0,1 ≈ 37,7 Ω.'),
    p(17, DEC, CIR, I.cirD51,
      '¿Cuál es aproximadamente la reactancia capacitiva de un capacitor de 100 µF a 60 Hz? (XC = 1 / (2πfC))',
      ['3,8 Ω', '265 Ω', '26,5 Ω'], 2,
      'XC = 1 / (2 × π × 60 × 0,0001) ≈ 26,5 Ω.'),
    p(18, DEC, CIR, I.cirD61,
      '¿Cuál diodo está diseñado para trabajar en polarización inversa, en la región de ruptura, para regular tensión?',
      ['Diodo rectificador', 'Diodo Zener', 'Diodo emisor de luz (LED)'], 1,
      'El diodo Zener mantiene una tensión casi constante en la región de ruptura inversa.'),
    p(19, DEC, CIR, I.cirD71,
      'Comparado con un rectificador de media onda, el rectificador de onda completa...',
      ['Aprovecha ambos semiciclos de la señal de entrada', 'Aprovecha únicamente el semiciclo positivo', 'No utiliza diodos'], 0,
      'El de onda completa rectifica los dos semiciclos, por lo que entrega una señal con más energía y menos rizado.'),

    // ===== UNDÉCIMO - Máquinas eléctricas (20-33) =====
    p(20, UND, MAQ, I.maq11,
      'En una máquina eléctrica rotativa, ¿cómo se llama la parte fija?',
      ['Rotor', 'Eje', 'Estator'], 2,
      'El estator es la parte fija y el rotor es la parte que gira.'),
    p(21, UND, MAQ, I.maq12,
      '¿Qué máquina eléctrica convierte energía mecánica en energía eléctrica?',
      ['Motor', 'Generador', 'Resistencia'], 1,
      'El generador transforma energía mecánica en eléctrica; el motor hace lo contrario.'),
    p(22, UND, MAQ, I.maq21,
      '¿Qué material se usa comúnmente como conductor en los devanados de motores y transformadores?',
      ['Cobre esmaltado', 'Porcelana', 'Vidrio'], 0,
      'El cobre esmaltado tiene baja resistividad y su esmalte aísla una espira de otra. La porcelana y el vidrio son aislantes.'),
    p(23, UND, MAQ, I.maq21,
      '¿Cuál de estos materiales se usa como aislante en los bobinados de máquinas eléctricas?',
      ['Alambre de cobre desnudo', 'Varilla de acero', 'Barniz dieléctrico o papel aislante'], 2,
      'El barniz dieléctrico y el papel aislante impiden que la corriente pase entre espiras o hacia el núcleo.'),
    p(24, UND, MAQ, I.maq31,
      'Un motor absorbe 5 kW de la red y entrega 4 kW en el eje. ¿Cuál es su eficiencia?',
      ['125 %', '80 %', '20 %'], 1,
      'Eficiencia = potencia de salida / potencia de entrada = 4 / 5 = 0,8 = 80 %.'),
    p(25, UND, MAQ, I.maq41,
      'En un generador de corriente continua, ¿qué componente rectifica mecánicamente la tensión alterna inducida en las bobinas?',
      ['Núcleo laminado', 'Conmutador con escobillas', 'Placa de datos'], 1,
      'El conmutador (colector) junto con las escobillas convierte la tensión alterna inducida en una tensión continua.'),
    p(26, UND, MAQ, I.maq41,
      '¿Qué factores modifican directamente la tensión generada en un generador de CC?',
      ['El color de la carcasa', 'La longitud del cable de tierra', 'La velocidad de giro y el flujo magnético del campo'], 2,
      'La tensión inducida es proporcional a la velocidad de giro y al flujo magnético.'),
    p(27, UND, MAQ, I.maq51,
      'El alternador de un automóvil produce corriente alterna trifásica que se convierte en corriente continua mediante...',
      ['Un transformador reductor', 'Un puente rectificador de diodos', 'Un capacitor de arranque'], 1,
      'El puente rectificador de diodos convierte la CA del alternador en CD para cargar la batería.'),
    p(28, UND, MAQ, I.maq51,
      '¿Cuál es la función del regulador de voltaje del alternador automotriz?',
      ['Arrancar el motor de combustión', 'Enfriar el aceite del motor', 'Mantener estable la tensión de carga de la batería'], 2,
      'El regulador controla la corriente de campo para que la tensión de carga se mantenga dentro de un rango estable.'),
    p(29, UND, MAQ, I.maq61,
      'En un motor de inducción trifásico, ¿qué ocurre al intercambiar dos de las tres fases de alimentación?',
      ['Se invierte el sentido de giro', 'El motor se detiene definitivamente', 'Su velocidad aumenta al doble'], 0,
      'Al intercambiar dos fases se invierte la secuencia y el campo giratorio cambia de sentido.'),
    p(30, UND, MAQ, I.maq71,
      'Un transformador reductor tiene una relación de espiras de 10:1. Si el primario recibe 2 400 V, ¿cuál es la tensión del secundario?',
      ['24 000 V', '240 V', '24 V'], 1,
      'Vs = Vp / 10 = 2 400 V / 10 = 240 V.'),
    p(31, UND, MAQ, I.maq71,
      '¿Qué dato de la placa de un transformador indica la potencia que puede entregar sin sobrecalentarse?',
      ['El número de serie', 'La fecha de fabricación', 'La potencia nominal en kVA'], 2,
      'La potencia nominal, expresada en kVA, es la que el transformador puede entregar de forma continua.'),
    p(32, UND, MAQ, I.maq81,
      'En una empresa, el cliente que recibe el trabajo dentro de la misma organización, por ejemplo otro departamento, es un...',
      ['Cliente externo', 'Cliente interno', 'Proveedor'], 1,
      'El cliente interno pertenece a la misma organización; el externo es quien compra o contrata fuera de ella.'),
    p(33, UND, MAQ, I.maq91,
      '¿Qué característica es propia de las personas que trabajan bien en equipo?',
      ['Trabajar aislados sin compartir información', 'Imponer siempre las decisiones propias', 'Comunicarse con respeto y compartir responsabilidades para un objetivo común'], 2,
      'El trabajo en equipo requiere comunicación, respeto y responsabilidad compartida para lograr una meta común.'),

    // ===== UNDÉCIMO - Automatismo electromecánico (34-45) =====
    p(34, UND, AUT, I.autU11,
      '¿Qué componente se usa a menudo para generar el pulso de disparo de un SCR o un TRIAC en circuitos de control de fase?',
      ['DIAC', 'Fusible', 'Bobina de contactor'], 0,
      'El DIAC entrega un pulso cuando la tensión alcanza su valor de ruptura y dispara la compuerta del SCR o del TRIAC.'),
    p(35, UND, AUT, I.autU11,
      'En un circuito de control de fase con TRIAC, ¿qué se modifica para variar la potencia entregada a la carga?',
      ['La temperatura ambiente únicamente', 'El ángulo de disparo', 'La frecuencia de la red eléctrica'], 1,
      'Al retrasar o adelantar el disparo en cada semiciclo cambia la parte de la onda que llega a la carga y, con ello, su potencia.'),
    p(36, UND, AUT, I.autU21,
      '¿Cuántos terminales tiene un SCR y cómo se llaman?',
      ['Dos: ánodo y cátodo', 'Cuatro: ánodo, cátodo, base y emisor', 'Tres: ánodo, cátodo y compuerta'], 2,
      'El SCR tiene ánodo, cátodo y compuerta (gate).'),
    p(37, UND, AUT, I.autU21,
      '¿Qué diferencia a un TRIAC de un SCR?',
      ['El TRIAC no tiene terminal de control', 'El TRIAC puede conducir en ambos sentidos de la corriente alterna', 'El TRIAC solo se usa en corriente continua'], 1,
      'El SCR conduce en un solo sentido; el TRIAC conduce en los dos, por eso se usa para controlar corriente alterna.'),
    p(38, UND, AUT, I.autU31,
      'Un IGBT combina la facilidad de control por tensión de un MOSFET con...',
      ['La capacidad de manejar altas corrientes propia de un transistor bipolar', 'La capacidad de funcionar sin fuente de energía', 'La ausencia de terminal de control'], 0,
      'El IGBT se controla por tensión en la compuerta y maneja corrientes altas con baja caída de tensión, como un transistor bipolar.'),
    p(39, UND, AUT, I.autU41,
      'Un temporizador 555 en configuración astable produce...',
      ['Un solo pulso cuando recibe un disparo', 'Un voltaje constante de CD', 'Una onda de pulsos continua, sin disparo externo'], 2,
      'En modo astable el 555 oscila solo, generando pulsos de forma continua. El modo monoestable da un solo pulso al ser disparado.'),
    p(40, UND, AUT, I.autU51,
      '¿Qué característica se atribuye a un amplificador operacional ideal?',
      ['Impedancia de entrada muy alta', 'Impedancia de entrada nula', 'Ganancia igual a cero'], 0,
      'El amplificador operacional ideal tiene impedancia de entrada infinita, ganancia infinita e impedancia de salida nula.'),
    p(41, UND, AUT, I.autU61,
      '¿En qué instalaciones se usan interruptores termomagnéticos de alta capacidad interruptiva?',
      ['En lámparas de escritorio', 'En tableros industriales o de distribución con corrientes de cortocircuito elevadas', 'En cargadores de celular'], 1,
      'La capacidad interruptiva es la corriente de cortocircuito que el interruptor puede cortar sin dañarse; en industria esos valores son altos.'),
    p(42, UND, AUT, I.autU71,
      'En un circuito de control a contactores, ¿qué dispositivo se usa para señalizar que un motor está en marcha?',
      ['Relé térmico', 'Fusible', 'Luz piloto'], 2,
      'La luz piloto es el dispositivo de señalización. El relé térmico protege contra sobrecarga y el fusible contra cortocircuito.'),
    p(43, UND, AUT, I.autU72,
      'Un temporizador que cierra su contacto un tiempo después de recibir energía en su bobina se clasifica como...',
      ['Temporizador a la conexión (retardo a la energización)', 'Temporizador a la desconexión', 'Relé de sobrecarga'], 0,
      'El retardo a la conexión (ON-delay) espera el tiempo ajustado después de energizarse antes de cambiar sus contactos.'),
    p(44, UND, AUT, I.autU81,
      'Para invertir el sentido de giro de un motor trifásico con contactores, el circuito de fuerza...',
      ['Conecta las tres fases en serie', 'Intercambia dos fases con dos contactores enclavados entre sí', 'Reduce la tensión de la red'], 1,
      'Se usan dos contactores que intercambian dos fases; el enclavamiento evita que ambos cierren a la vez y causen un cortocircuito.'),
    p(45, UND, AUT, I.autU91,
      'En un motor de dos velocidades tipo Dahlander, la velocidad se cambia modificando...',
      ['La resistencia del cable de tierra', 'El tamaño del ventilador', 'La conexión de los devanados para cambiar el número de polos'], 2,
      'En el motor Dahlander se cambia la conexión de los devanados para variar el número de polos y, con ello, la velocidad.'),

    // ===== DUODÉCIMO - Automatismo electromecánico (46-51) =====
    p(46, DUO, AUT, I.autD101,
      '¿Qué parte del PLC ejecuta el programa de control?',
      ['La CPU (unidad central de procesamiento)', 'El módulo de salidas a relé', 'La fuente de alimentación'], 0,
      'La CPU lee las entradas, ejecuta el programa y actualiza las salidas.'),
    p(47, DUO, AUT, I.autD101,
      '¿Qué módulo de un PLC conecta los sensores y pulsadores con la CPU?',
      ['Módulo de salidas', 'Módulo de entradas', 'Puerto de programación'], 1,
      'El módulo de entradas recibe las señales de sensores y pulsadores y las adapta para la CPU.'),
    p(48, DUO, AUT, I.autD111,
      '¿Qué propiedad diferencia al aire comprimido de un fluido hidráulico como el aceite?',
      ['Ambos son igual de compresibles', 'El aire es incompresible y el aceite se comprime fácilmente', 'El aire es compresible; el aceite es prácticamente incompresible'], 2,
      'El aire se comprime y se expande, por eso los movimientos neumáticos son más elásticos. El aceite casi no se comprime, por eso permite mayores fuerzas y movimientos más precisos.'),
    p(49, DUO, AUT, I.autD121,
      'Para regular la presión de trabajo en un sistema neumático, ¿qué elemento se ajusta?',
      ['El regulador de presión de la unidad de mantenimiento', 'El silenciador', 'El cilindro de simple efecto'], 0,
      'El regulador de presión fija la presión de trabajo que se envía al circuito.'),
    p(50, DUO, AUT, I.autD121,
      '¿Qué válvula se usa para regular la velocidad de un cilindro neumático?',
      ['Válvula de simultaneidad', 'Válvula reguladora de caudal (estranguladora)', 'Manómetro'], 1,
      'La válvula reguladora de caudal limita el aire que entra o sale del cilindro y así controla su velocidad.'),
    p(51, DUO, AUT, I.autD131,
      '¿Cuál es un tipo de robot industrial cuyo brazo tiene articulaciones giratorias, parecido a un brazo humano?',
      ['Robot cartesiano', 'Robot móvil sin brazo', 'Robot articulado'], 2,
      'El robot articulado tiene juntas giratorias. El cartesiano se mueve en línea recta sobre tres ejes.'),

    // ===== DUODÉCIMO - Circuitos electromecánicos (52-60) =====
    p(52, DUO, CIR, I.cirU11,
      '¿Cuántos símbolos distintos usa el sistema de numeración hexadecimal?',
      ['8', '16', '10'], 1,
      'El sistema hexadecimal usa 16 símbolos: del 0 al 9 y de la A a la F.'),
    p(53, DUO, CIR, I.cirU12,
      '¿Cuál es el equivalente decimal del número binario 1011?',
      ['13', '9', '11'], 2,
      '1011 = 8 + 0 + 2 + 1 = 11.'),
    p(54, DUO, CIR, I.cirU21,
      '¿Qué compuerta lógica entrega un 1 en la salida solo cuando sus dos entradas están en 1?',
      ['AND', 'OR', 'NOR'], 0,
      'La compuerta AND solo da 1 cuando todas sus entradas valen 1.'),
    p(55, DUO, CIR, I.cirU22,
      'Al simplificar con álgebra booleana la expresión A + A·B se obtiene...',
      ['A·B', 'A', 'A + B'], 1,
      'Por absorción: A + A·B = A·(1 + B) = A·1 = A.'),
    p(56, DUO, CIR, I.cirU31,
      'Una ventaja de la familia CMOS frente a la TTL es...',
      ['Una velocidad siempre mayor', 'Un consumo de energía mayor', 'Un consumo de potencia mucho menor en reposo'], 2,
      'Los circuitos CMOS consumen muy poca potencia cuando no conmutan, por eso se usan en equipos con baterías.'),
    p(57, DUO, CIR, I.cirU31,
      '¿Cuál es la tensión de alimentación típica de los circuitos integrados TTL estándar?',
      ['3 V', '5 V', '24 V'], 1,
      'La familia TTL estándar se alimenta con 5 V.'),
    p(58, DUO, CIR, I.cirU41,
      '¿Cuál es el resultado de sumar 101 + 011 en binario?',
      ['0110', '1110', '1000'], 2,
      '101 (5) + 011 (3) = 8, que en binario es 1000.'),
    p(59, DUO, CIR, I.cirU51,
      'En un biestable SR construido con compuertas NAND, las entradas son activas en...',
      ['Nivel bajo (0)', 'Nivel alto (1)', 'Flanco de subida del reloj'], 0,
      'El latch SR con compuertas NAND se activa con nivel bajo (0) en las entradas; con compuertas NOR, con nivel alto.'),
    p(60, DUO, CIR, I.cirU52,
      'En una compuerta lógica, ¿qué mide el tiempo de propagación?',
      ['La cantidad de entradas de la compuerta', 'El voltaje máximo de alimentación', 'El retardo entre el cambio en la entrada y el cambio en la salida'], 2,
      'El tiempo de propagación es el retraso con que la salida responde a un cambio en la entrada.'),
  ],
};